server:
  port: ${PORT:8089}
spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://task-db:5432/postgres
    username: postgres
    password: example
eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/